name: "Hello world workflow"

on:
  push:
    branches:
      - master
      - prduction

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: "Print Hello World"
        run: echo "Hello world"